# configuration
application:
    port: 8884
    host: 127.0.0.1
database:
    host: "localhost"
    port: 3306
    username: ""
    password: ""
    database_name: ""
email:
    host: "smtp.mailtrap.io"
    port: 2525
    username: ""
    password: ""

